#!/bin/bash

# NOTE: app dependency dirs are in host-mounted dirs for reuse between app deployments.
# NOTE: Docker logging is disabled because the log would be identical to the gateway log file.

set -e

source ./config/.env

# If the PGHOST is a UNIX socket, we need to mount the socket
if [[ "$PGHOST" == '/'* ]];
then
  PGHOST_SOCKET="$PGHOST"
fi

sudo docker \
  run \
    --name nymtc_tig_gateway_dev \
    -it \
    --rm \
    --log-driver none \
    --env-file ./config/.env \
    ${PGHOST_SOCKET:+-v "$PGHOST_SOCKET":"$PGHOST_SOCKET"} \
    -v "$PWD/mount_dirs/gateway":/home/deploy/gateway \
    -v "$PWD/mount_dirs/.bundle":/home/deploy/.bundle \
    -v "$PWD/mount_dirs/.rvm":/home/deploy/.rvm \
    -v "$PWD/dev-environment/gateway-tests":/home/deploy/gateway-tests \
    -v "$PWD/dev-environment/gateway-tests/gateway_ruby_spec.rb":/home/deploy/gateway/spec/gateway_ruby_spec.rb \
    "${GATEWAY_DOCKER_IMG}-dev-environment" \
    bash -l
