#!/bin/bash -l

set -e
set -a

source /home/deploy/.bashrc

cd /home/deploy/gateway/

touch "/home/deploy/gateway/log/$RAILS_ENV.log"

./deploy/restart

tail -f "/home/deploy/gateway/log/$RAILS_ENV.log"
