#!/bin/bash -l

# This script will
#
#  0. The Docker container must be created with --env-file config/.env
#
#  1. Install all the app dependencies.
#     These are installed in ~/.rvm, ~/.bundle, ~/.gem.

set -e
set -a

cd /home/deploy/gateway/

bundle update bootstrap3-datetimepicker-rails
bundle install --without test development --full-index

# Copy the dependencies files to the host
cp -r /home/deploy/.rvm/* /home/deploy/.rvm.host
cp -r /home/deploy/.gem/* /home/deploy/.gem.host
cp -r /home/deploy/.bundle/* /home/deploy/.bundle.host
